alias ls='ls -lh --color=auto'
alias ll='ls -lh --color=auto'
alias la='ls -Alh --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias rr='rm -rf'
alias md='mkdir -p'
alias c='clear'

alias psgr='ps aux | grep'
